### ISSUE TITLE
Semver?

### ISSUE THREAD

**Issue by dragontoe** [woohoolabs/yin#1]
Hi!

Does this library use [semantic versioning](http://semver.org)? 

If semver is used it would be good if the Readme mention it.

Thanks!

**Comment by kocsismate** [comment]
Hey,

Yes, it does! Thanks for the notice, I'll add versioning information later this afternoon.

Reminder: until reaching version 1.0, minor versions can (and likely will) introduce breaking changes. But according to my plans, the public API will become quite stable until version 0.7

**Comment by kocsismate** [comment]
Done.
