### ISSUE TITLE
Error in createResourceIdInvalidException

### ISSUE THREAD

**Issue by Ilyes512** [woohoolabs/yin#100]
The DefaultExceptionFactory::createResourceIdInvalidException method contains an error.

```php
    // WoohooLabs\Yin\JsonApi\Exception\DefaultExceptionFactory 

    /**
     * @param mixed $id
     */
    public function createResourceIdInvalidException($id): JsonApiExceptionInterface
    {
        return new ResourceIdInvalid($id);
    }
```
Source: https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Exception/DefaultExceptionFactory.php#L163-L169

The method clearly wants to receive the $id value, but when we look at the `ResourceIdInvalid`-exception class you can see it wants the type of the id instead. When given a incorrect id (for example an integer id `100`). It will throw an error because it expected a string.

```php
    // WoohooLabs\Yin\JsonApi\Exception\ ResourceIdInvalid

    public function __construct(string $type)
    {
        parent::__construct("The resource ID must be a string instead of $type!", 400);
        $this->type = $type;
    }
```
Source: https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Exception/ResourceIdInvalid.php#L17-L21

This can be solved easily in two ways:

1. Change the initiation of the exception to `new ResourceIdInvalid(gettype($id));`
2. Update all calls to `createResourceIdInvalidException` by adding the `gettype` there ([Only 4 in this lib it self](https://sourcegraph.com/github.com/woohoolabs/yin@master/-/blob/src/JsonApi/Exception/DefaultExceptionFactory.php#L166:21=&tab=references))

Let me know what you think.

**Comment by kocsismate** [comment]
Thank you very much for the report! I'll have a look at it in the following days.

**Comment by kocsismate** [comment]
I fixed the issue in master by following your first suggestion. I believe this solution has the advantages of
- being less of a BC break
- being the correct thing to do, and the other similar `DefaultExceptionFactory` methods should follow this change in the next major version

I'll release a new patch version as soon as you confirm that the commit fixed your issue.

**Comment by Ilyes512** [comment]
Looks good! See https://github.com/woohoolabs/yin/issues/97#issuecomment-760832036
