### ISSUE TITLE
Parsed body always contains an empty array when using Symfony requests

### ISSUE THREAD

**Issue by Ilyes512** [woohoolabs/yin#101]
So first of.. I am using Symfony HttpFoundation requests (actually Laravel's request class, but that is just a child class of the Symfony request). So, I use the library in combination with [psr-http-message-bridge](https://github.com/symfony/psr-http-message-bridge) to get Psr requests.

With this [commit](https://github.com/woohoolabs/yin/commit/0817ab3e2e6c0de17a56c2b3e18ac8b59873d9eb) you added a check to the `validateTopLevelMembers()`-method. But this won't work for me because the `getParsedBody()` will always return an empty array when one uses the bridge. See:
- https://github.com/symfony/psr-http-message-bridge/blob/main/Factory/PsrHttpFactory.php#L71
- https://github.com/symfony/http-foundation/blob/5.x/ParameterBag.php#L38

This might be more of a issue with the bridge then it is with this library, but maybe the check could be improved?

**Comment by kocsismate** [comment]
ah, I had a suspicion that the emptiness check was added at some point as a workaround for some library's non-standard behaviour... I wouldn't have thought that it's Symfony.  But I don't get what the point is of initializing the parsed body to `[]` when in fact there is no body?

Nevertheless, let's try to come up with a solution for your problem:
- I could go with checking the methods instead (what you suggested), but I don't think that's the right approach. JSON:API doesn't say that all `POST`, `PUT` etc. requests must contain a valid `JSON:API` document. It only says that all valid JSON:API documents must contain any of the `data`, `errors`, and `meta` top-level members, but `data` and `errors` must not be both present.
- I can make the validation a bit more lax, and do not invoke a validation error when the document is empty. It unfortunately does not follow the spec 100%, but maybe it's a good compromise...

How does the 2nd option sound for you? Do you see any other possibility?

**Comment by samijnih** [comment]
Hello!

I have this issue too so I had to rollback to 4.1.2 atm

**Comment by kocsismate** [comment]
@samijnih I've just reverted that particular change which caused the trouble. Sorry for the inconvenience! I'll release it as soon as CI is green.

**Comment by samijnih** [comment]
@kocsismate ty :)

Hope that we found a solution! :)
