### ISSUE TITLE
[PHP8] Method ReflectionParameter::getClass() is deprecated

### ISSUE THREAD

**Issue by QassaDevelopers** [woohoolabs/yin#105]
In the `HydratorTrait` class, the method `getArgumentTypeHintFromCallable` triggers a PHP deprecation notice: 
> Method ReflectionParameter::getClass() is deprecated

```
    protected function getArgumentTypeHintFromCallable(callable $callable): ?string
    {
        $function = &$callable;
        $reflection = new ReflectionFunction(Closure::fromCallable($function));
        $arguments  = $reflection->getParameters();
        $class = isset($arguments[1]) ? $arguments[1]->getClass() : null;

        if ($class === null) {
            return null;
        }

        return $class->getName();
    }
```

According to the [PHP docs](https://www.php.net/reflectionparameter.getClass), the `getType()` method is recommended. This method may return a [`ReflectionNamedType`](https://www.php.net/manual/en/class.reflectionnamedtype.php) or a [`ReflectionUnionType`](https://www.php.net/manual/en/class.reflectionuniontype.php) class.

There is a small [example code](https://www.php.net/manual/en/reflectionparameter.gettype.php#example-5139) available on how to work with these.

As I am not  familiar (enough) with this package, I am unsure as what the `getArgumentTypeHintFromCallable` method should return. I therefor have not created a PR.

I would really appreciate if this error could be fixed, so I can use this package in my PHP8 project.

I also think that this would be a backward incompatible change because the `getType()` method behaves different on other php versions.

Thanks in advance. Any feedback is welcome.

**Comment by QassaDevelopers** [comment]
To clarify: something like this would work (needs null checks etc):
`$arguments[1]->getType()->getName()`

but I am not sure how to behave when the `getType()` is a `ReflectionUnionType`. What should the classname be in that case? Or is a union typehint simply not allowed (supported)?

**Comment by kocsismate** [comment]
Hi!

Thanks for the report, I've just added a new commit to the 5.0 branch: https://github.com/woohoolabs/yin/commit/ae6ba421c631948b8c0ec286d8d55b35527692f2

Neither `ReflectionUnionType`, nor `ReflectionIntersectionType` (a new PHP 8.1 feature) is allowed.

**Comment by QassaDevelopers** [comment]
Hi!

Thanks for the quick reply and thanks for fixing it! Issue resolved afaic.
