### ISSUE TITLE
Data Transformer array_merge problem

### ISSUE THREAD

**Issue by ArrayIterator** [woohoolabs/yin#108]
https://github.com/woohoolabs/yin/blob/346041a6cd8442e22ea4b9999f453bbb96e7a03b/src/JsonApi/Transformer/DocumentTransformer.php#L77

Document transformer [transformMetaMembers()](https://github.com/woohoolabs/yin/blob/346041a6cd8442e22ea4b9999f453bbb96e7a03b/src/JsonApi/Transformer/DocumentTransformer.php#L70) will reset array keys to increment value / integer when meta contains numeric `float|int|number(int)string` offset

> Meta Values

```php
$meta  = [
    "123" => 'value 1',
    'key' => 'value 2',
    456 =>  'value 3',
    789.0 =>  'value 4',
    112.1 =>  'value 5',
    '112.2' = 'value 6'
];
```

> Result

```json
{
    "jsonapi": {
        "version": "1.1"
    },
    "meta": {
        "0": "value 1",
        "key": "value 2",
        "1": "value 3",
        "2": "value 4",
        "3": "value 5",
        "112.2": "value 6"
    },
    "data": {
        "id": "node",
        "type": "custom",
        "attributes": []
    }
}
```

Suggest to using lopp rather than `array_merge`, cause array_merge will use renumbered the keys is float or integer
Ref https://www.php.net/manual/en/function.array-merge.php

**Comment by kocsismate** [comment]
Thanks for the report! It is a valid problem, and I agree with the suggested fix. Do you want to provide a fix?

**Comment by ArrayIterator** [comment]
> Thanks for the report! It is a valid problem, and I agree with the suggested fix. Do you want to provide a fix?

Just pull small codes as I can.

https://github.com/woohoolabs/yin/pull/110
