### ISSUE TITLE
PATCH a relationship with {"data":null}

### ISSUE THREAD

**Issue by dimvic** [woohoolabs/yin#15]
According to the specification issuing a `PATCH` request which includes a relationship with a `{"data":null}` body should clear the relationship, but in `HydratorTrait->hydrateRelationships()` this is found:

```
if (empty($data["relationships"])) {
    return $domainObject;
}
```

which results in the relationship hydrator never being called, is that intentional?

Of course one can override `hydrateRelationships()`, but shouldn't the defaults conform to the standards?

**Comment by kocsismate** [comment]
That's really clever! I'll look at it tomorrow!

**Comment by kocsismate** [comment]
Sorry for being late, I had other works to do during the week.

So I investigated the problem and found that you mean the [updating relationships part](http://jsonapi.org/format/#crud-updating-relationships) of the spec, and I had to realize that currently, hydrators only work well when you want to [update or create resources](http://jsonapi.org/format/#crud).

As we talked that hydrators need some improvement anyway, I'll try to address this deficiency in v0.11. But now, I'll release the version with your other patches! Thank you for your help :)

**Comment by dimvic** [comment]
No prob, my pleasure :) I don't have a use case this bug affects yet, I just thought it's quite an important point in the docs that should be supported, that's why I reported it...
Eagerly waiting for 0.10.2 for now!

**Comment by kocsismate** [comment]
I am closing this issue as the feature in question was implemented in https://github.com/woohoolabs/yin/pull/33 though it will need some small adjustments and additions. So v0.11 is not far away, I want to make it happen in 1-2 weeks!

**Comment by kocsismate** [comment]
My latest commit brings full support for this feature: https://github.com/woohoolabs/yin/commit/b11718cdd5fc7d592ff5475701c262334f3cccf5

Test it if you have some time :)
