### ISSUE TITLE
ResourceIdentifier does not consider "data" key

### ISSUE THREAD

**Issue by qpautrat** [woohoolabs/yin#16]
Hi there,

As JSON API specification says 

> If a relationship is provided in the relationships member of the resource object, its value MUST be a relationship object with a **data** member.

Correct me if i'm wrong, but [ResourceIdentifier](https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Schema/ResourceIdentifier.php#L24) does not care about this `data` key.
And as we pass complete array in [Request](https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Request/Request.php#L521) it results as `null`.

You can try it with this simple example from JSON API documentation:

``` json
{
  "data": {
    "type": "photos",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },
    "relationships": {
      "photographer": {
        "data": { "type": "people", "id": "9" }
      }
    }
  }
}
```

**Comment by christophehurpeau** [comment]
:+1:

**Comment by dimvic** [comment]
This type of query is exactly what's supported by the implementation though, `ResourceIdentifier` is what encapsulates the data for each relationship object, for example:

``` json
//query
{
  "data": {
    "type": "photos",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },
    "relationships": {
      "photographer": {
        "data": { "type": "people", "id": "9" }
      },
      "others": {
        "data": [
          { "type": "other", "id": "1" },
          { "type": "other", "id": "2" }
        ]
      }
    }
  }
}
```

``` php
//ToOneRelationship hydrator
function($domainObject, $relationship, $data, $relationshipName) {
    $resourceIdentifier = $relationship->getResourceIdentifier();
    //$resourceIdentifier->getType() is "people"
    //$resourceIdentifier->getId() is "9"
    ...
}

//ToManyRelationship hydrator
function($domainObject, $relationship, $data, $relationshipName) {
    foreach ($relationship->getResourceIdentifiers() as $resourceIdentifier) {
        //$resourceIdentifier->getType() is "other"
        //$resourceIdentifier->getId() is "1", then "2"
        ...
    }
    ...
}
```

**Comment by qpautrat** [comment]
I don't get it @dimvic .

`$jsonApi->getRequest()->getResourceToOneRelationship('photographer')` returns `null` and it should not.

**Comment by kocsismate** [comment]
My fear is that [`$request->getResourceToOneRelationship()`](https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Request/Request.php#L529) does not return any value. I have already fixed some similar issues in the past, but sometimes I just forget about the `return` statement. :D

Anyway, thanks for catching this problem! I can fix it right now, but can only assure if it really works in the evening.

**Comment by kocsismate** [comment]
I found another bug with the aformentioned method, so I fixed it. Feel free to reopen the issue if you find it otherwise!
