### ISSUE TITLE
jsonApi

### ISSUE THREAD

**Issue by dragontoe** [woohoolabs/yin#23]
I'm running some schema-validation on the output from yin and stumble upon a small issue. It looks like yin is creating the [JSON API Object](http://jsonapi.org/format/#document-jsonapi-object) with the key "jsonApi", but the doc always write it in all lowercase.  

https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Document/AbstractDocument.php#L78

**Comment by kocsismate** [comment]
Fair point, I'll fix it in the evening! Thank you very much for this!

**Comment by kocsismate** [comment]
Resolved in the following commit:https://github.com/woohoolabs/yin/commit/37e09c065f90c54f089d9a117391324c7baa9953, released as 0.10.6
