### ISSUE TITLE
OffsetPagination bug, offset and limit mixup

### ISSUE THREAD

**Issue by dragontoe** [woohoolabs/yin#25]
Hi,

It looks like $defaultOffset and $defaultLimit is sent in the wrong order [here](https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Request/Request.php#L399)

...($this->getPagination(), $defaultLimit, $defaultOffset);
should be
...($this->getPagination(), $defaultOffset, $defaultLimit);

**Comment by kocsismate** [comment]
Hey,

You are right, thank your very much for the effort! I've just fixed it in my recent commit: https://github.com/woohoolabs/yin/commit/102eba3d172bb746f384833ca9cda49a3d16de12

I am currently releasing Yin 0.10.7. :)
