### ISSUE TITLE
Hydrate attribute with NULL

### ISSUE THREAD

**Issue by qpautrat** [woohoolabs/yin#28]
Hi fellows,

I need your POV on this one.
Correct me if i'm wrong but I should be able to set an attribute to my domain object to null if want to.
But as we can see [there](https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Hydrator/HydratorTrait.php#L94) hydration will be forgotten.
Thereby I'm not able to delete my field description for example.

Thx.

**Comment by kocsismate** [comment]
Yes, you are absolutely right! Really important observation, so thank you very much!

Do you agree with using the `array_key_exists()` function instead of `isset()`? I think this is the correct fix for it.

**Comment by qpautrat** [comment]
PR open @kocsismate !
