### ISSUE TITLE
Example of how to do multi-level relationship?

### ISSUE THREAD

**Issue by mmucklo** [woohoolabs/yin#3]
Do you have any examples of how to do a multi-level includes?

For example include=comments,comments.authors?  (and have it return the right things)

The problem we're seeing is when you try to do multi-level documents it seems to break on validateRelationships -

e.g.

``` php
$article = new ArticleDocument(new ArticleResourceTransformer(new CommentResourceTransformer(new AuthorResourceTransformer())));
```

When CommentResourceTransformer defines a getRelationships($comment) of type "author", it seems to also get validated looking for "comments" in this case and then throws an exception out of "validateRelationships".

**Comment by kocsismate** [comment]
You are right, thanks for the report! The `validateRelationships` method fails indeed, and it seems like the path of the currently processed relationship (`$transformation->basePath`) doesn't get updated. So I will be working on the patch in the following days.

**Comment by kocsismate** [comment]
Anyway, I added a new resource to the [book example](https://github.com/woohoolabs/yin/blob/master/examples/Book/Action/GetBookAction.php) to manually test multi-level relationships. If you set up a web server as mentioned in the Read Me, this example will be available at {{ YOURHOST }}?example=book&id=1&include=authors,publisher,publisher.representative (and it currently throws an exception).

**Comment by mmucklo** [comment]
Ok thanks for the follow up...

**Comment by kocsismate** [comment]
My last commit (https://github.com/woohoolabs/yin/commit/a7c6a706cc82efaebfc622625e7441c4167f3efb) hopefully fixed the bug in dev-master. Could you please confirm it? If the patch seems to be OK, I'll release version 0.10. In v0.11, I plan to increase test coverage and test quality to avoid issues like this.

**Comment by mmucklo** [comment]
I think it may be fixed, but please stand by, I should know better by early next week...

**Comment by kocsismate** [comment]
Take your time, I am looking forward to your response next week! But I am going to release v10 shortly, as the popularity of Yin has just "skyrocketed" in the past 2 days, doubling its stargazers, and I don't want new people to use the older version without some important fixes in dev-master. I'll release a patch version if something is still missing from my fix.

**Comment by mmucklo** [comment]
Ok the main issue is fixed.  There are two "sub-issues" if you would, however I'm going to open two new issues on those.

**Comment by kocsismate** [comment]
Thanks! I am interested in the issues!
