### ISSUE TITLE
Clearing relationship is broken in master branch

### ISSUE THREAD

**Issue by emil-nasso** [woohoolabs/yin#36]
Something with the new validation seems to have been broken my last PR. I'm looking into it, i just wanted to flag for it here (i read that you were planning to do a release).

**Comment by emil-nasso** [comment]
Nevermind. There was an error in one of my tests.

It was trying to clear a relationship using:

``` json
"relationships": {
            "foobar": {
                "data": {
                    "type": "accounts",
                    "id": null
                }
            },
```

Instead of: 

``` json
"relationships": {
            "foobar": {
                "data": null
            },

```

And i don't think that form is supported, can't find anything about it in the specification.

Sorry about this false alarm.

![https://media.giphy.com/media/xT1XGwu6nmcfEXPqUM/giphy.gif](https://media.giphy.com/media/xT1XGwu6nmcfEXPqUM/giphy.gif)

**Comment by kocsismate** [comment]
No problem :P
