### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by kocsismate** [woohoolabs/yin#39]
Test coverage could be improved for some key classes. See the "Test coverage" column here:
https://scrutinizer-ci.com/g/woohoolabs/yin/code-structure/master?elementType=class&orderField=test_coverage&order=asc&changesExpanded=0

**Comment by jmauerhan** [comment]
As a Test Engineer, I'd love to work on this :) I'll open a PR tomorrow with a few classes.

**Comment by kocsismate** [comment]
I would be really-really happy if you could help as I didn't really have time for this lately :/ Feel free to reach out to me if you need any guidance where to start!

**Comment by Djuki** [comment]
@jmauerhan @kocsismate 

If you need more help on this, ping me I can take over few classes too.

**Comment by kocsismate** [comment]
@Djuki I would be very happy if you could help!

Any method that's not yet covered and implements more logic than returning/setting a value definitely needs more testing. But I have found errors when testing getters/setters so you can choose whatever you prefer to test. :)

**Comment by Djuki** [comment]
@kocsismate Ok.

I was thinking to start with `Negotiation/MessageValidator.php`

I noticed that in `lintMessage` we have `new JsonParser()` which makes us hard to mock it.

Same in `validateMessage` with `new RefResolver` and `new Validator`

Do you plan to use some DI or I should unit test this class as is now.

**Comment by kocsismate** [comment]
Yeah, not long ago I was thinking about this problem too, but finally I didn't change the current implementation because I considered those 3rd party classes as implementation details. I don't usually do this, but here I felt that it is much simpler to leave them as-is than introducing a level of indirection.

So I would prefer test it as is now. :)

**Comment by jmauerhan** [comment]
The `new JsonParser` can be mocked with Mockery if it needs to be. I haven't had a chance to start adding any tests yet, but I'll do a small PR with some examples.
