### ISSUE TITLE
How to skip a level in a multi-level relationship

### ISSUE THREAD

**Issue by mmucklo** [woohoolabs/yin#4]
If I want to include a sub-level but skip the intermediary level, it doesn't seem to work.

However I want to preface this with two things:
1. I may be reading the jsonapi spec incorrectly on this (I don't know if there's a good concrete example)
2. I may be misunderstanding how to use woohoolabs/yin

What I want to do in the following example is to include comments.authors, but not comments.  I'm presuming (and here where I could be wrong, so feel free to correct me), but I'm guessing that the right way to do this, according to the spec is simply:

```
include=comments.authors
```

However with yin, it seems that I get back both the comments and the authors, instead of just the authors.

**Comment by kocsismate** [comment]
The spec says the following in the "Inclusion of Related Resources" section:

> Note: Because compound documents require full linkage (except when relationship linkage is excluded by sparse fieldsets), intermediate resources in a multi-part path must be returned along with the leaf nodes. For example, a response to a request for comments.author should include comments as well as the author of each of those comments.

So the current behaviour is a requirement of the spec.

But the next paragraph states the following:

> Note: A server may choose to expose a deeply nested relationship such as comments.author as a direct relationship with an alias such as comment-authors. This would allow a client to request /articles/1?include=comment-authors instead of /articles/1?include=comments.author. By abstracting the nested relationship with an alias, the server can still provide full linkage in compound documents without including potentially unwanted intermediate resources.

So skipping a relationship level is only an additional functionality servers can provide. Some months ago, I tried to implement it, but it proved to be really complex. Anyway, I'll have a look at it again if I can find an efficient solution to the problem.

**Comment by mmucklo** [comment]
Ok thanks for clarifying - I suppose the best solution might be to do
sparse fieldsets on the intermediate resources then...

**Comment by kocsismate** [comment]
This idea is really good indeed until the feature is implemented.

**Comment by kocsismate** [comment]
I'll close this as it is too complex to develop and the gain is not so much.
