### ISSUE TITLE
PageBasedPaginationProviderTrait getPrevLink and getNextLink generate wrong links

### ISSUE THREAD

**Issue by pdrosos** [woohoolabs/yin#48]
Hi,

first thank you for the great library! I use it in my project with Zend Expressive and it helped me a lot to implement JSONAPI.

I use the PageBasedPaginationProviderTrait to generate pagination links and I found out it generates Prev and Next links wrong.

The Prev link is null on the last page and the Next link is null on the page before the last page.
The problem is [here](https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Schema/Pagination/PageBasedPaginationLinkProviderTrait.php#L66) and [here](https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Schema/Pagination/PageBasedPaginationLinkProviderTrait.php#L79).
I believe that `|| $this->getPage() >= $this->getLastPage()` should be removed from line 66 and `$this->getPage() + 1 >= $this->getLastPage()` should become `$this->getPage() >= $this->getLastPage()` on line 79.

Please let me know if this is correct and if I should make a PR to fix it. Thanks!

**Comment by kocsismate** [comment]
I am glad to hear that you use the library! :) I'll definitely look at the problem and tell you if I also believe your fix is good as soon as possible (it's probably tomorrow or Saturday).

**Comment by kocsismate** [comment]
@pdrosos Ok, I had time to think about what you said and it really looks good! So I would be happy to receive that PR :)

**Comment by pdrosos** [comment]
Done in #49 :)
