### ISSUE TITLE
ResourceNotFound should have 404 status (?)

### ISSUE THREAD

**Issue by leclairmael** [woohoolabs/yin#56]
Hello,

Currently the ResourceNotFound exception bears a 400 status.
I believe it would make more sense to make it a 404.
Or maybe there's a specific reason behind this?

Cheers

**Comment by kocsismate** [comment]
Hi!

Oh my.. You are completely right. I will definitely fix it (and check all the other exceptions too) tonight and release a new patch version.

Thank you for reporting this!

**Comment by kocsismate** [comment]
I've just released v1.0.4! :)
