### ISSUE TITLE
Resource schema validating

### ISSUE THREAD

**Issue by oitimon** [woohoolabs/yin#59]
Hello.

When you POST or PATCH "id" with integer value (for example {"id": 23}) the library generates system exception because of new stricts (strict_types=1) in file \WoohooLabs\Yin\JsonApi\Schema\ResourceIdentifier  line 38.

Old version worked with integers because of autocasting in php. I think new version "must" generate "4XX Bad Request, id must be a string" (jsonapi 1.0 standard) or in fast way just to cast value to string, like:

line 38: $resourceIdentifier->setId((string)$array["id"]);

Anyway it's not cool to get 500 when the mistake is in client's requests.

Thanks for your work and library!

**Comment by kocsismate** [comment]
Hi! Thank you for the report!

I tried to fix the issue in this commit (https://github.com/woohoolabs/yin/commit/4957da51783992add389b531b58d2f6b960e242a) and I hope it will work for you. Please tell me if you still have any problem with type hints.

**Comment by oitimon** [comment]
It works perfect.

Thank you!
