### ISSUE TITLE
Body sent via POST is not retrievable

### ISSUE THREAD

**Issue by leclairmael** [woohoolabs/yin#64]
Hello,

Starting a project with current 2.0.2, I'm facing an issue when trying to send POST requests.
Basically the retrieved body ends up being empty, which causes fatal errors.

I've identified the issue to be coming from `WoohooLabs\Yin\JsonApi\Request\Request::getParsedBody`, I'll post a PR shortly.

**Comment by leclairmael** [comment]
Here's the PR https://github.com/woohoolabs/yin/pull/65

**Comment by kocsismate** [comment]
Fixed.
