### ISSUE TITLE
Instruction lacking information on examples

### ISSUE THREAD

**Issue by piiskop** [woohoolabs/yin#72]
I followed the instructions on how to install yin. However, I can't run examples as the instruction is lacking information on how to do that. It'w written that I should run composer install inside yin. OK, did it, it created another vendor folder inside yin and yin was in another vendor folder already as I used composer to install yin for my project. Installing yin using composer doesn't install the folder examples, only src. And inside installed yin folder, running composer install installs a lot of stuff but not the examples folder. Please fix that. I want to use a library for JSON API standard that has validation and everything implemented, however yin and yang seem to be overly complicated as there's no easy tutorial that covers all the cases of CRUD unless it's the folder examples that I can't get to work.

**Comment by kocsismate** [comment]
Hey,

Thank you for the feedback! I'll try to update the install documentation with instructions how to get the examples soon. Until then, you can use multiple methods to get the examples:

- Use the `--prefer-source` attribute when installing Yin (https://getcomposer.org/doc/03-cli.md#require)
- Download the whole project by clicking the "Clone or Download" button on the project's main GitHub page

I hope that I could help you :)

**Comment by kocsismate** [comment]
Closing this, as I fixed it here: cb909939d0efe4c1ec588e53e9bcfc57bbc63750.
