### ISSUE TITLE
Recommandation for a symfony based implementation

### ISSUE THREAD

**Issue by waghanza** [woohoolabs/yin#73]
Hi,

I want to create a `symfony` `4` based **hateos** api that follow [jsonapi specs](http://jsonapi.org)

I can find to valuable implementations :

+ https://repo.packagist.org/packages/qpautrat/woohoolabs-yin-bundle
+ https://repo.packagist.org/packages/paknahad/jsonapi-bundle

Those implementations are very similar. On documentation, I can see a link for https://repo.packagist.org/packages/qpautrat/woohoolabs-yin-bundle.

@qpautrat @paknahad Your implementations are very similar. 

Is there a way to **combine** efforts made ?

Regards,

**Comment by qpautrat** [comment]
Hello @waghanza ,

I didn't look at @paknahad's bundle but these bundles are just a bridge between `Yin` framework and `Symfony` Framework.
There is no much things to do. 
You just need to ask yourself if `Yin` (and `Symfony`) is the correct tool for your need. If yes it does not really matter what implementation you chose IMHO.
If `Yin` does not change in a critical way how it works, you should be fine with one of them for a long time.

**Comment by paknahad** [comment]
Hello everybody
I agree with @qpautrat 

I don't think these bundles are same, so you can select one of these based on your need.
