### ISSUE TITLE
Nullable attributes in database

### ISSUE THREAD

**Issue by waghanza** [woohoolabs/yin#74]
Hi @kocsismate,

I have some `nullable` fields in my **database**, then the value of `$attribute` is **null** in
https://github.com/woohoolabs/yin/blob/159c654e1dcf933eb2ac1eea9082366737ec8171/src/JsonApi/Transformer/AbstractResourceTransformer.php#L126

Is this legitimate to encapse this with a `is_null` or any check that could avoid **Function name must be a string**

Regards,

**Comment by kocsismate** [comment]
Hi @waghanza,

Could you please show me an example transformer from where this error is thrown? I have a guess that something is misconfigured at your end, because the `$attribute` here should be a `callable` which is an element in the returned array of the `getAttributes()` method. This is an example `Resource Transformer` from an API of mine:

```php
/**
 * @param Address $resource
 */
public function getAttributes($resource): array
 {
    return [
        "country" => function (Address $resource) {
            return [
                "code" => $resource->getCountry()->getCode(),
                "name" => $resource->getCountry()->getName(),
            ];
        },
        "region" => function (Address $resource) {
            return $resource->getRegion();
         },
        "city" => function (Address $resource) {
            return $resource->getCity();
        },
        "postal_code" => function (Address $resource) {
            return $resource->getPostalCode();
        },
        "address_line" => function (Address $resource) {
            return $resource->getAddressLine();
        },
    ];
}
```

**Comment by waghanza** [comment]
Hi @kocsismate ,

Considering your example, I have to deal with `nullable` address line in database

The function signature is :
~~~php
public function getAddressLine(): ?string
~~~

Regards,

**Comment by waghanza** [comment]
Hi @kocsismate,

Globally, the variable `$attribute` is not always a **string** (at least for me, so not callable as a **method**)
https://github.com/woohoolabs/yin/blob/159c654e1dcf933eb2ac1eea9082366737ec8171/src/JsonApi/Transformer/AbstractResourceTransformer.php#L126

Regards,

**Comment by waghanza** [comment]
@kocsismate perhaps my `getAttributes` **method** is not well written

**Comment by kocsismate** [comment]
Yes, I think so! You have to use anonymous function in the returned array too (as in the example above)

**Comment by waghanza** [comment]
@kocsismate Here is my function defintion
~~~
return [
            'customer' => function (array $order) {
                return $order->getCustomerId()
            },
        ];
~~~
and `getCustomerId()` returns an `int`

**Comment by kocsismate** [comment]
hmm. but this definition seems to be correct (apart from that the `$order` parameter isn't an `array`, but I guess that is just an oversight)! Do you still experience the `Function name must be a string` error?

**Comment by waghanza** [comment]
@kocsismate sure, wrong copy/paste (for array type-int)
~~~php
public function getAttributes($order): array
    {
        return [
            'customer' => function (Order $order) {
                return (string) $order->getCustomerId()
            },
        ];
    }
~~~

**Comment by waghanza** [comment]
@kocsismate the problem was not were I thought, I've fixed it now
