### ISSUE TITLE
Bulk creation / update

### ISSUE THREAD

**Issue by waghanza** [woohoolabs/yin#77]
Hi @kocsismate,

I can see that we can `GET` compound document
https://jsonapi.org/format/upcoming/#document-compound-documents

Can this also be done for creation at the moment ?

Regards,

**Comment by kocsismate** [comment]
Hi @waghanza ,

No, unfortunately the spec doesn't have this thing yet. But it has been long time on their roadmap, so JSON:API will probably support this in the future...

I'm closing this ticket for now. :)
