### ISSUE TITLE
[NFR] Let user install PSR to allow PSR extension

### ISSUE THREAD

**Issue by ruudboon** [woohoolabs/yin#78]
I'm using a PSR extension for my PSR interfaces (https://github.com/jbboehr/php-psr) due to the requirements of the PSR package from packagist that one is used.
Could you remove that package as a requirement from the composer.json and let the user decide where to get the interface from?

**Comment by kocsismate** [comment]
Hi @ruudboon 

I wouldn't really like to remove the PSR interfaces from composer.json, but fortunately there is a workaround for your problem, which is mentioned in the readme of the extension: https://github.com/jbboehr/php-psr#using-with-composer

Would it work for you?

**Comment by ruudboon** [comment]
That's how I solved it now so fine by me. In this case I would implement this myself as a suggested package but it's up to you. Thnx.
