### ISSUE TITLE
Example of a document that uses AbstractSimpleResourceDocument

### ISSUE THREAD

**Issue by Ilyes512** [woohoolabs/yin#79]
Hi,

I started implementing yin into my project and thought lets start with the "simple", but I don't seem to be able to figure out how to implement it. It's mainly the (uncommented) abstract `getResource()`-method that's causing the problem.

I haven't tried the AbstractSingleDocument yet, but I am sure that's going to be easy to use (because of the great readme and examples 👍 ).

So my question (request) is if you could provide use with an example of how to use AbstractSimpleResourceDocument.

Thanks in advance!

**Comment by Ilyes512** [comment]
I found out how to implement the AbstractSimpleResourceDocument getResource() method. For anyone else that might wonder how it's done. Here is a minimal example:

```php
    protected function getResource(): array
    {
        return [
            'type'       => '<type>',
            'id'         => '<ID>',
            'attributes' => [
                'key' => 'value',
            ],
        ];
    }
```

**Comment by kocsismate** [comment]
Hi! Thanks for the report, I'll definitely try to better document this document type.

One more thing: there is a version 4.0 of Yin in the works so you could directly go with it. It is still in beta, but I want to release a final version very soon.

**Comment by Ilyes512** [comment]
I just noticed that but good to know your planning on releasing it soon. I will definitely try and use that then.

**Comment by kocsismate** [comment]
I have been delaying the release because the JSON:API 1.1 spec hasn't been finalized yet, but I don't want to wait forever so I'll just go with the current RC version (and only with partial support for profiles).
