### ISSUE TITLE
Possible bug in OffsetBasedPagination

### ISSUE THREAD

**Issue by koichirose** [woohoolabs/yin#83]
From my tests I'm getting wrong results here: https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Schema/Pagination/OffsetBasedPaginationLinkProviderTrait.php#L35

In case of 5 total items and limit 100, it will return a negative offset.
In case of 5 total items, offset = 0, limit = 1, it will return offset 3, limit 1, therefore missing the last item.

And here: https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Schema/Pagination/OffsetBasedPaginationLinkProviderTrait.php#L39

With 5 total items, offset 4, limit 1, I get no prev link (should be offset 3, limit 1).

I'll try to check it out later on.

**Comment by kocsismate** [comment]
Hi @koichirose ,

Did you have time to check it out? If not, I'll try to check it in the near future.

**Comment by koichirose** [comment]
I managed to reproduce it with the input I specified, but I didn't have time to actually fix it properly.

**Comment by kocsismate** [comment]
Thank you very much for the great examples! I pushed a fix for them to master (https://github.com/woohoolabs/yin/commit/f417f6682af3051d117126f5f4f6f7d74302a918), please verify if pagination works correctly for you.

**Comment by koichirose** [comment]
Hello! Yes, that fixes it. Thanks

**Comment by kocsismate** [comment]
Glad to hear it! I'll create a new release shortly.

**Comment by kocsismate** [comment]
The fix has just been released. :)
