### ISSUE TITLE
Exception code 0 

### ISSUE THREAD

**Issue by jakagacic** [woohoolabs/yin#84]
Hi!

Exceptions in namespace `WoohooLabs\Yin\JsonApi\Exception` don't have correct codes, they all use default code 0, without the possibility of overriding. This makes it harder to handle these errors. For example, [`FullReplacementProhibited`](https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Exception/FullReplacementProhibited.php) should have code 403.

Libraries like [jsonapi bundle](https://github.com/paknahad/jsonapi-bundle), that is commonly used with yours, depend on the code to [format errors](https://github.com/paknahad/jsonapi-bundle/issues/40) correctly, so it would be nice to have this fixed.

I could make a PR containing the necessary changes if you agree.

**Comment by kocsismate** [comment]
Hi @jakagacic ,

Thanks for the feedback, I'd appreciate a PR. :)

**Comment by kocsismate** [comment]
Your changes have just been released! :)
