### ISSUE TITLE
How to hydrate a POST request with multiple resources

### ISSUE THREAD

**Issue by Doqnach** [woohoolabs/yin#88]
Given the following JSON:API payload for a POST request:

```json
{
    "data": [
        {
            "id": "my-id1",
            "type": "MyResource",
            "attributes": {
                "a": 1
            }
        },
        {
            "id": "my-id2",
            "type": "MyResource",
            "attributes": {
                "a": 2
            }
        }
    ]
}
```

How do you correctly hydrate this?

```php
$resources = $jsonApi->hydrate(new \App\JsonApi\Hydrator\MyResource(), []);
```

The problem being the above call ends up treating `$request->getResource()` as a single resource (see `CreateHydratorTrait::hydrateForCreate()`), even though this is multiple...

There is no "CreateBooks" example (https://github.com/woohoolabs/yin/blob/master/examples/Book/Action/CreateBookAction.php).

**Comment by Doqnach** [comment]
Right now I'm using this workaround... which is very ugly.

```php
$hydrator = new DomainObjectHydrator();
$request = $jsonApi->getRequest();
$body = $request->getParsedBody();
$objects = [];
foreach ($request->getParsedBody()['data'] as $data) {
    $body['data'] = $data;
    $jsonApi->setRequest($request->withParsedBody($body));

    $object = new DomainObject();
    $objects[] = $jsonApi->hydrate(
        $hydrator,
        $object
    );
}
```

**Comment by Doqnach** [comment]
I actually re-read the spec, and found the following:

https://jsonapi.org/format/#crud-creating

> A resource can be created by sending a `POST` request to a URL that represents a collection of resources. The request **MUST** include a _single_ resource object as primary data.

With the emphasis on '_single_ resource'.

So this explains also why Yin does not support the above behaviour... it is following the spec. 

https://discuss.jsonapi.org/t/alternative-ways-to-update-multiple-objects/952/2

**Comment by kocsismate** [comment]
Hey @Doqnach ,

Yes, you are right! The JSON:API spec doesn't currently support modifying multiple resources in one request. There is a very early issue filed for this, but the details are still not finalized: https://github.com/json-api/json-api/issues/795.

**Comment by Doqnach** [comment]
Since this is intended behaviour by the spec, even though I disagree with the spec 😛 , I will close this issue.
