### ISSUE TITLE
Problem with recursive relations

### ISSUE THREAD

**Issue by hiqsol** [woohoolabs/yin#95]
I have mutually related entities: tariff plan includes prices and price has reference to the tariff plan..

And when converting a plan with prices to JsonApi I receive error:

`Maximum function nesting level of '500' reached, aborting! in /app/vendor/woohoolabs/yin/  src/JsonApi/Schema/Relationship/AbstractRelationship.php`

This issue is related to #67 but it is not the same. I've already solved problem with instantiating resources. The infinite loop occurs in resource transformation:

```
...
woohoolabs/yin/src/JsonApi/Schema/Relationship/AbstractRelationship.php:191  
woohoolabs/yin/src/JsonApi/Schema/Relationship/ToManyRelationship.php:35  
woohoolabs/yin/src/JsonApi/Schema/Relationship/AbstractRelationship.php:244  
woohoolabs/yin/src/JsonApi/Transformer/ResourceTransformer.php:37   
woohoolabs/yin/src/JsonApi/Transformer/ResourceTransformer.php:155  
woohoolabs/yin/src/JsonApi/Transformer/ResourceTransformer.php:187  
...
```

It just doesn't stop. It transforms plan then price then plan then price then ...
I thought it should check if it has already transformed an object with given ID and don't go deeper.

Maybe I'm doing something wrong?

Any help appreciated! Thanks!

**Comment by kocsismate** [comment]
@hiqsol Can you tell me why a price includes a plan as a relationship? By the first look, this relationship makes sense only the other way around for me.

Nevertheless, you can define valid relationships via the `ResourceInterface::getRelationships()` method, so
even if your objects have recursive relations, you can do the following:
- you add `price` as a relationship in  `PlanResource::getRelationships()`
- you remove `plan` as a relationship in `PriceResource::getRelationships()`

Please correct me if I didn't understand your problem well! :)
