### ISSUE TITLE
AbstractLinks::transform() generates invalid "prev" / "next" links

### ISSUE THREAD

**Issue by ettoredn** [woohoolabs/yin#96]
`AbstractLinks::transform()` sets "prev" and "next" to `null` when there is only one page in the result set. This does not pass JSON:API schema validation.

For instance, the following response does not pass schema validation:
```json
{
  "jsonapi": {
    "version": "1.0"
  },
  "links": {
    "self": "/v1/transactions?page%5Bnumber%5D=1&page%5Bsize%5D=100",
    "first": "/v1/transactions?page%5Bnumber%5D=1&page%5Bsize%5D=100",
    "last": "/v1/transactions?page%5Bnumber%5D=1&page%5Bsize%5D=100",
    "prev": null,
    "next": null
  },
  "data": [
    {
      "type": "transactions",
      "id": "1",
      "links": {
        "self": "/v1/transactions/1"
      },
      "attributes": {
        "timestamp": "2020-07-01T07:01:24.450+00:00",
        "symbol": "TSLA",
        "amount": -20,
        "price": 950.12
      }
    }
  ]
}
```

This is probably a problem with the spec itself that mandates each link be either a string or an object with `href` and `meta`, while at the same time stating that a pagination link key could be either omitted or null. *Schema validation would pass if keys are omitted instead of being set to null*.

**Comment by ettoredn** [comment]
https://github.com/json-api/json-api/issues/887

**Comment by kocsismate** [comment]
@ettoredn Yes, you're right, the problem is with the spec itself.

**Comment by kocsismate** [comment]
Since I'm not going to backport fixes for the official schema, I've just added an optional constructor parameter for `ResponseValidator` to be able to provide a custom schema path which potentially has upstream fixes.
